namespace: get_edi_io
name: debian_setup
version: 1.0.0
readme: README.md
authors:
  - Matthias Luescher <lueschem@gmail.com>
description: Debian recipes that extend and complement the edi tool.
license:
  - MIT
tags: [linux, tools, edi, debian]
repository: https://github.com/lueschem/debian_setup
documentation: https://docs.get-edi.io
homepage: https://www.get-edi.io/
issues: https://github.com/lueschem/debian_setup/issues
build_ignore: []
