---
- name: Enable foreign architectures.
  ansible.builtin.command: bash -c "dpkg --add-architecture {{ item }} && touch /etc/{{ item }}.enabled.edi"
  args:
    creates: /etc/{{ item }}.enabled.edi
  loop: "{{ cross_architectures }}"

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
