---
- name: Remove service startup prevention.
  ansible.builtin.file:
    dest: /usr/sbin/policy-rc.d
    state: absent

- name: Remove unused packages.
  ansible.builtin.apt:
    autoremove: true
  when: edi_create_distributable_image

# Due to https://github.com/ansible/ansible/issues/82611 we are using apt-get clean directly here.
- name: Clean apt cache. # noqa command-instead-of-module
  ansible.builtin.command: apt-get -y clean
  changed_when: false
  when: edi_create_distributable_image

- name: Identify apt lists.
  ansible.builtin.find:
    paths: /var/lib/apt/lists
    patterns: "*"
  register: apt_lists
  when: edi_create_distributable_image

- name: Remove apt lists that will get re-downloaded using apt-get update.
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  when: edi_create_distributable_image and not item.path == "/var/lib/apt/lists/lock"
  loop: "{{ apt_lists.files }}"
