---
- name: Enforce host uid and gid for local installations to enable shared folders.
  set_fact:
    enforced_gid: "{{ edi_current_user_gid }}"
    enforced_uid: "{{ edi_current_user_uid }}"
  when: not edi_configure_remote_target

- name: Add a group for the current user.
  group:
    name: "{{ edi_current_user_group_name }}"
    gid: "{{ enforced_gid | default(omit) }}"
    state: present

- name: Add the current user.
  user:
    name: "{{ edi_current_user_name }}"
    group: "{{ edi_current_user_group_name }}"
    uid: "{{ enforced_uid | default(omit) }}"
    shell: /bin/bash
    groups: adm,sudo
    password: "$6$nqXAG09MHYE$MZ6kZGJyVcU6ETl.YjCs0fX9y0BOA3qzTkjgoYYUceT4tTgaVbVs0Aeh4kBZqLqLRlSrzhLKLOCEV/uUagm351"
    append: yes
    update_password: on_create

- name: Enable sudo without password for the development user.
  template: src=no_passwd dest=/etc/sudoers.d/{{ edi_current_user_name }}

- name: Set up authorized keys for current user.
  authorized_key:
    user: '{{ edi_current_user_name }}'
    state: present
    key: '{{ item }}'
  with_file: '{{ edi_current_user_ssh_pub_keys }}'

- name: Export display.
  lineinfile:
    dest: /home/{{ edi_current_user_name }}/.profile
    line: export DISPLAY=:0
  when: export_display
