---
- name: Create documentation directory within artifact.
  ansible.builtin.file:
    dest: "{{ documentation_directory }}"
    state: directory
    mode: '0755'
  when: document_build_setup or document_installed_packages

- name: Get project configuration scm revision.
  ansible.builtin.script: get_project_scm_revision {{ edi_project_directory }}
  delegate_to: 127.0.0.1
  register: project_scm_revision
  changed_when: false
  become: false
  when: document_build_setup

- name: Write build information file.
  ansible.builtin.template:
    src: build.yml
    dest: "{{ documentation_directory }}/{{ build_documentation_file }}"
    mode: '0644'
  when: document_build_setup

- name: Generate a list of installed packages.
  ansible.builtin.command: "{{ package_documentation_command }}"
  register: installed_packages
  changed_when: false
  when: document_installed_packages

- name: Write a file that documents the installed packages.
  ansible.builtin.template:
    src: packages
    dest: "{{ documentation_directory }}/{{ package_documentation_file }}"
    mode: '0644'
  when: document_installed_packages

- name: Document the packages baseline.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ documentation_directory }}/{{ package_baseline_documentation_file }}"
    mode: '0644'
  with_first_found:
    - files:
      - "{{ package_baseline_source_file }}" # noqa: yaml
      skip: true
  when: document_installed_packages
