---
- name: Setup /etc/environment (set proxies).
  lineinfile:
    dest: /etc/environment
    regexp: '^{{ item.key }}=.*'
    line: '{{ item.key }}="{{ item.value }}"'
    create: yes
    mode: 0644
  loop: "{{ proxy_configs }}"
  no_log: True # do not reveal passwords
  when: item.value != ""

- name: Setup /etc/environment (unset proxies).
  lineinfile:
    dest: /etc/environment
    regexp: '^{{ item.key }}=.*'
    state: absent
  loop: "{{ proxy_configs }}"
  no_log: True # do not reveal passwords
  when: item.value == ""

# Remark: When using ansible_connection=lxd /etc/environment does not get sourced.
#         For this reason we also add this settings to .bashrc of root.
- name: Setup /root/.bashrc (set proxies).
  lineinfile:
    dest: /root/.bashrc
    regexp: '^export {{ item.key }}=.*'
    line: 'export {{ item.key }}="{{ item.value }}"'
    create: yes
    mode: 0644
  loop: "{{ proxy_configs }}"
  no_log: True # do not reveal passwords
  when: item.value != ""

- name: Setup /root/.bashrc (unset proxies).
  lineinfile:
    dest: /root/.bashrc
    regexp: '^export {{ item.key }}=.*'
    state: absent
  loop: "{{ proxy_configs }}"
  no_log: True # do not reveal passwords
  when: item.value == ""

- name: Setup /etc/apt/apt.conf.d/50proxy (set proxies).
  lineinfile:
    dest: /etc/apt/apt.conf.d/50proxy
    regexp: '^{{ item.apt_key }} '
    line: '{{ item.apt_key }} "{{ item.value }}";'
    create: yes
    mode: 0644
  loop: "{{ proxy_configs }}"
  no_log: True # do not reveal passwords
  when: item.value != "" and item.apt_key != ""

- name: Setup /etc/apt/apt.conf.d/50proxy (unset proxies).
  lineinfile:
    dest: /etc/apt/apt.conf.d/50proxy
    regexp: '^{{ item.apt_key }} '
    state: absent
  loop: "{{ proxy_configs }}"
  no_log: True # do not reveal passwords
  when: item.value == "" and item.apt_key != ""
