---
- name: Setup /etc/environment (set proxies).
  ansible.builtin.lineinfile:
    dest: /etc/environment
    regexp: '^{{ item.key }}=.*'
    line: '{{ item.key }}="{{ item.value }}"'
    create: true
    mode: '0644'
  loop: "{{ proxy_configs }}"
  no_log: true # do not reveal passwords
  when: item.value | length > 0

- name: Setup /etc/environment (unset proxies).
  ansible.builtin.lineinfile:
    dest: /etc/environment
    regexp: '^{{ item.key }}=.*'
    state: absent
  loop: "{{ proxy_configs }}"
  no_log: true # do not reveal passwords
  when: not item.value | length > 0

# Remark: When using ansible_connection=lxd /etc/environment does not get sourced.
#         For this reason we also add this settings to .bashrc of root.
- name: Setup /root/.bashrc (set proxies).
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    regexp: '^export {{ item.key }}=.*'
    line: 'export {{ item.key }}="{{ item.value }}"'
    create: true
    mode: '0644'
  loop: "{{ proxy_configs }}"
  no_log: true # do not reveal passwords
  when: item.value | length > 0

- name: Setup /root/.bashrc (unset proxies).
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    regexp: '^export {{ item.key }}=.*'
    state: absent
  loop: "{{ proxy_configs }}"
  no_log: true # do not reveal passwords
  when: not item.value | length > 0

- name: Setup /etc/apt/apt.conf.d/50proxy (set proxies).
  ansible.builtin.lineinfile:
    dest: /etc/apt/apt.conf.d/50proxy
    regexp: '^{{ item.apt_key }} '
    line: '{{ item.apt_key }} "{{ item.value }}";'
    create: true
    mode: '0644'
  loop: "{{ proxy_configs }}"
  no_log: true # do not reveal passwords
  when: item.value | length > 0 and item.apt_key | length > 0

- name: Setup /etc/apt/apt.conf.d/50proxy (unset proxies).
  ansible.builtin.lineinfile:
    dest: /etc/apt/apt.conf.d/50proxy
    regexp: '^{{ item.apt_key }} '
    state: absent
  loop: "{{ proxy_configs }}"
  no_log: true # do not reveal passwords
  when: not (item.value | length > 0 and item.apt_key | length > 0)
