---
- name: Install base development tools.
  ansible.builtin.apt:
    name: "{{ base_development_tools }}"
    state: present
  when: install_development_tools

- name: Install cross development tools.
  ansible.builtin.apt:
    name: "{{ cross_development_tools }}"
    state: present
  when: install_cross_development_tools

- name: Install crossbuild essentials.
  ansible.builtin.apt:
    name: crossbuild-essential-{{ item }}
    state: present
  loop: "{{ cross_architectures }}"
  when: install_cross_development_tools

- name: Install foreign base libraries.
  ansible.builtin.apt:
    name: "{{ item.0 }}:{{ item.1 }}"
    state: present
  loop: "{{ foreign_base_libraries | product(cross_architectures) | list }}"
  when: install_cross_development_tools
